Neos:
  Fusion:
    defaultContext:
      CsvPO: 'Sitegeist\CsvPO\Eel\TranslationHelper'

  Neos:
    modules:
      administration:
        submodules:
          translation:
            label: 'Translations'
            description: 'Show and alter component translations'
            icon: 'language'
            controller: 'Sitegeist\CsvPO\Controller\TranslationController'
            privilegeTarget: 'Sitegeist.CsvPO:ManageTranslationLabels'

Sitegeist:
  CsvPO:
    debugMode: false
    management:
      packageKeys: []
      locales: []
      fileExtension: '.translation.csv'
      resourcePath: 'Private/Fusion'


